### ISSUE TITLE
componentWillReceiveProps will eventually be deprecated.

### ISSUE THREAD

**Issue by strommj** [freeranger/react-bootstrap-tabs#11] opened 2020-04-08 01:25 UTC
> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

**Comment by lidaof** [comment] 2020-06-25 03:25
just forked and renamed the methods, https://www.npmjs.com/package/react-bootstrap-tabs-rename-unsafe-lifecycles

**Comment by freeranger** [comment] 2020-06-27 11:28
@lidaof If you'd like to submit a PR, I can merge it in

**Comment by lidaof** [comment] 2020-06-27 15:29
nice, I will create a PR. I thought you are not maintaining this package...thank you so much!

**Comment by freeranger** [comment] 2020-07-04 15:30
@lidaof I merged in your changes but got a failing test which I have now had to mark as skipped:
`should call UNSAFE_componentWillReceiveProps when a property changes`

It requires a load of package upgrades which was resulting in me disappearing down a rabbit hole of deps and bugs and conflicts, so I reverted it.
It would be great if you could get the test running again - the problem is that the version of enzyme does not support UNSAFE_xxx and upgrading that caused more issues.

The real answer of course is to upgrade the component completely to a newer version of react, but I no longer have either the time or the react skills to do so (I stopped front end development about 3 years ago, so bit of a learning curve to get up to speed again :/)

**Comment by lidaof** [comment] 2020-07-04 15:48
ha, i see, thank you @freeranger . I will take a look, I am also at learning stage, I will see what I can do. thank you again for the nice package.

**Comment by freeranger** [comment] 2020-07-05 11:35
@lidaof I took some time out today in the end - wasn't as bad as I had thought ;)
Published v2.0.0 which removes the deprecated properties and works with react 16.3.1

**Closed as completed by freeranger** 2020-07-05 11:35 UTC

**Comment by lidaof** [comment] 2020-07-05 14:52
nice, thank you @freeranger
